#!/bin/bash

CONF_DIR=conf
OUTPUT_DIR=$CONF_DIR/examples
FILES=(
    "tomcat/tomcat-users.xml"
    "tomcat/server.xml"
    "apache2/sites-available/000-default.conf"
    "apache2/ports.conf"
)

echo "excuting precommit....."

for file in "${FILES[@]}"; do
    if [ -f "$CONF_DIR/$file" ]; then
        output_directory="$(dirname "$OUTPUT_DIR/$file.example")"
        output_file="$OUTPUT_DIR/$file.example"

        if [ ! -d "$output_directory" ]; then
          mkdir -p "$output_directory"
        fi
        
        sudo cp -v "$CONF_DIR/$file" "$output_file"

        # Add the file to git only if it has changes
        if ! git diff --quiet "$output_file"; then
            git add "$output_file"
        fi
    fi
done